#!/usr/bin/env bash

# 1.1 Downloading ocp crc comand cli and archive crc to local PATH
wget https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
xz xz -d crc-linux-amd64.tar.xz
cp crc-linux-1.24.0-amd64/crc /usr/local/bin

curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm-ubuntu16.04 > docker-machine-driver-kvm
sudo mv docker-machine-driver-kvm /usr/local/bin/
sudo chmod +x /usr/local/bin/docker-machine-driver-kvm

# 1.2 Required software packages
sudo apt update;sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system network-manager -y

# 1.3 Installing CodeReady Containers
# sudo addgroup libvirtd
sudo usermod -a -G libvirtd $(whoami)
newgrp libvirtd

crc config set skip-check-user-in-libvirt-group true
systemctl is-active libvirtd
sudo systemctl start libvirtd
sudo systemctl enable libvirtd
sudo systemctl start NetworkManager
systemctl enable NetworkManager

# 1.4 Setting up CodeReady Containers
crc setup

# 1.5 Starting the virtual machine
# Image pull secret: {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3poaXdlaWNuaWJtY29tMWxsaHJrYXNxbnhrbXVxbXZsd2ZybHNxdGFrOlo4V0ZYTEpYOUkxRE0zNEdTTVpSNThVTENNWVZCQ0tHS09HTzhVRFE2UUlTMldOMlZNOUgyWUNQTEVXVjVWWUU=","email":"zhiwei@cn.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3poaXdlaWNuaWJtY29tMWxsaHJrYXNxbnhrbXVxbXZsd2ZybHNxdGFrOlo4V0ZYTEpYOUkxRE0zNEdTTVpSNThVTENNWVZCQ0tHS09HTzhVRFE2UUlTMldOMlZNOUgyWUNQTEVXVjVWWUU=","email":"zhiwei@cn.ibm.com"},"registry.connect.redhat.com":{"auth":"NTI1ODcwOTN8dWhjLTFMTEhya2FzcU5Ya21VUW1WTFdmckxzUVRBSzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJabU5tTXpRNVptUTVPRFEwTlRVNVltUXpNekEwWlRZNVpqYzJOVFpoTVNKOS50TEhnWDFSaXpNdGpmUUlyRGJ2TkkxbUdyR1BiWFI1TmR2TVEyX1oyd2FYTkc2eFJ1b25xSC11ZkZVMEx4Q2hLYWRSRV80bXNDZDNQSHlrQUV3UkdxVHc1aGg0WU1RdXNrdXdfUy1uUlU1WXhYVU9WdFpxd2F5Ykhkc19seVNBN29mMXY1Y2wzRklucExCd0dXV19kblRaN01Fb3dWcGZDUlRqRFF5cDExOWlqWWZkTDByZzNmOUFvMm9ZaWxRR1ZjSzRNVHBqWXR2ZFVnSF9GdWRoRTBVb05Ca2tNOER1aW90UDIwT2YzRkRqd0liN0xfaG5GeTVTSEdYWWhZUWhQTXNNdGJMeTJ1SXVTdGRKUm5UMEdPOVQ4em8yZm9zaExsYm5TZUViblBjb2gwR3gxQmtEcERyVkhTSEk5SVplQTVZRVdIaWpaVFhnb3BCSDljdGZiMHJYeE9saVRhLUNfa2U4RDFrODExUXhBcjIxd1doTnJxQ0wwai1Mc01JcnB5Y0ROLUZXaEkwY2hqT3MybGJuNV9VYlVxS09JcFNWNXNOZVYyU2JyQW9HWFZmVENuSGczQWRjTklZV3hLWGxncGhhVmloTHVpazF5WDIzU3RydlJIZmhMRTFzTUs0OUFiWmNsbEQ2bHE1MXQ1VjYtaHZkbGZwcllZbDZMeWF3UDV0ZXQ2TlBsUXhyYmVWeTJGMXFUcVVFd1dqM19ETmQ0b0dmTTdrVjRZNE5SWFBfYm1IdmtkaUF0ZkZVWS1IN1F1al96dHhCUWxEOHF1UERERzBGWXJFV1VMQ3o4aUp6dmxnZlBrTS1sTzJReTJBUXZHeHJ6VGxDbllSaFBqay1hMENmWHNOejFOYnJzT1kzTk80OHcyTDU5SXJndUt5R3pQZUhxTWFfNDBUQQ==","email":"zhiwei@cn.ibm.com"},"registry.redhat.io":{"auth":"NTI1ODcwOTN8dWhjLTFMTEhya2FzcU5Ya21VUW1WTFdmckxzUVRBSzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJabU5tTXpRNVptUTVPRFEwTlRVNVltUXpNekEwWlRZNVpqYzJOVFpoTVNKOS50TEhnWDFSaXpNdGpmUUlyRGJ2TkkxbUdyR1BiWFI1TmR2TVEyX1oyd2FYTkc2eFJ1b25xSC11ZkZVMEx4Q2hLYWRSRV80bXNDZDNQSHlrQUV3UkdxVHc1aGg0WU1RdXNrdXdfUy1uUlU1WXhYVU9WdFpxd2F5Ykhkc19seVNBN29mMXY1Y2wzRklucExCd0dXV19kblRaN01Fb3dWcGZDUlRqRFF5cDExOWlqWWZkTDByZzNmOUFvMm9ZaWxRR1ZjSzRNVHBqWXR2ZFVnSF9GdWRoRTBVb05Ca2tNOER1aW90UDIwT2YzRkRqd0liN0xfaG5GeTVTSEdYWWhZUWhQTXNNdGJMeTJ1SXVTdGRKUm5UMEdPOVQ4em8yZm9zaExsYm5TZUViblBjb2gwR3gxQmtEcERyVkhTSEk5SVplQTVZRVdIaWpaVFhnb3BCSDljdGZiMHJYeE9saVRhLUNfa2U4RDFrODExUXhBcjIxd1doTnJxQ0wwai1Mc01JcnB5Y0ROLUZXaEkwY2hqT3MybGJuNV9VYlVxS09JcFNWNXNOZVYyU2JyQW9HWFZmVENuSGczQWRjTklZV3hLWGxncGhhVmloTHVpazF5WDIzU3RydlJIZmhMRTFzTUs0OUFiWmNsbEQ2bHE1MXQ1VjYtaHZkbGZwcllZbDZMeWF3UDV0ZXQ2TlBsUXhyYmVWeTJGMXFUcVVFd1dqM19ETmQ0b0dmTTdrVjRZNE5SWFBfYm1IdmtkaUF0ZkZVWS1IN1F1al96dHhCUWxEOHF1UERERzBGWXJFV1VMQ3o4aUp6dmxnZlBrTS1sTzJReTJBUXZHeHJ6VGxDbllSaFBqay1hMENmWHNOejFOYnJzT1kzTk80OHcyTDU5SXJndUt5R3pQZUhxTWFfNDBUQQ==","email":"zhiwei@cn.ibm.com"}}}
crc start
